TEAM1_COUNTER_FIRST_DIGIT.width = MAIN_DIGIT_WIDTH;
TEAM1_COUNTER_FIRST_DIGIT.height = MAIN_DIGIT_HEIGHT;

TEAM1_COUNTER_SECOND_DIGIT.width = MAIN_DIGIT_WIDTH;
TEAM1_COUNTER_SECOND_DIGIT.height = MAIN_DIGIT_HEIGHT;

TEAM2_COUNTER_FIRST_DIGIT.width = MAIN_DIGIT_WIDTH;
TEAM2_COUNTER_FIRST_DIGIT.height = MAIN_DIGIT_HEIGHT;

TEAM2_COUNTER_SECOND_DIGIT.width = MAIN_DIGIT_WIDTH;
TEAM2_COUNTER_SECOND_DIGIT.height = MAIN_DIGIT_HEIGHT;

MINUTES_FIRST_DIGIT.width = MAIN_DIGIT_WIDTH;
MINUTES_FIRST_DIGIT.height = MAIN_DIGIT_HEIGHT;

MINUTES_SECOND_DIGIT.width = MAIN_DIGIT_WIDTH;
MINUTES_SECOND_DIGIT.height = MAIN_DIGIT_HEIGHT;

SECONDS_FIRST_DIGIT.width = MAIN_DIGIT_WIDTH;
SECONDS_FIRST_DIGIT.height = MAIN_DIGIT_HEIGHT;

SECONDS_SECOND_DIGIT.width = MAIN_DIGIT_WIDTH;
SECONDS_SECOND_DIGIT.height = MAIN_DIGIT_HEIGHT;

PERIOD_COUNTER.width = PERIOD_DIGIT_WIDTH;
PERIOD_COUNTER.height = PERIOD_DIGIT_HEIGHT;